### ISSUE TITLE
Unable to download GCC dataset

### ISSUE THREAD

**Issue by BashCache** [taohan10200/NLT#2]
Hi,
I am unable to download the GCC dataset from the provided links. It says the file would have been expired. .Could you please provide thw the GCC dataset. Thanks in advance :)
![image](https://user-images.githubusercontent.com/59500529/142907306-24c4130e-63d6-444d-bdaf-0c4f4e18f934.png)

**Comment by taohan10200** [comment]
I don't know why that happen to you, the three links are still available under my test,
    - the source dataset: GCC [[Link1](https://mailnwpueducn-my.sharepoint.com/:f:/g/personal/gjy3035_mail_nwpu_edu_cn/Eo4L82dALJFDvUdy8rBm6B0BuQk6n5akJaN1WUF1BAeKUA?e=ge2cRg)] [[Link2](https://v2.fangcloud.com/share/4625d2bfa9427708060b5a5981)] [[Link3](https://pan.baidu.com/s/1OtKqmw84TFbxAiN0H2xBtQ) (pwd:**utdo**)]

**Comment by BashCache** [comment]
Thank you, I am able to access through the above links now :)
